[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "https://threed-city-backend.onrender.com/api/:splat"
  status = 200
  force = true

# NOTE: For development, use localhost. For production, this is set to your deployed backend URL.
