services:
  - type: web
    name: 3d-city-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      # Add any other environment variables here
    autoDeploy: true
    rootDir: .
