services:
  - type: web
    runtime: python
    name: 3d-city-backend
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask run"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
    rootDir: backend
